allow specifying of source-repository for "simple-cfg"
It will likely be useful (especially if target-registry imposes
length-restrictions) to strip replication-source-prefix from replicated
OCI-Artefacts. Hence extend simple-cfg command to optionally allow
passing-in source-repository for convenience.

diff --git a/ctt/simple-cfg b/ctt/simple-cfg
--- a/ctt/simple-cfg
+++ b/ctt/simple-cfg
@@ -6,12 +6,46 @@ set -euo pipefail
 #
 # needs a single argument, which is used as target_repository
 
-if [ $# != 1 ]; then
-  echo "usage: ${BASH_SOURCE[0]} ocm-repository"
+usage() {
+cat <<EOF
+Prints a simple "processing.cfg" file for CTT.
+
+usage: ${BASH_SOURCE[0]} --target ocm-target-repository [--source ocm-source-repository]
+
+--target specifies the OCI-Registry to replicate to (also considered OCM-Repository-Root).
+
+if --source (which refers to replication source) is specified, it will be stripped from
+OCI-Image-References in replication-target. This is useful for targets where maximum allowed
+length is limited.
+EOF
+}
+
+if [ $# == 0 ]; then
+  usage
   exit 1
 fi
 
-target_registry=$1
+while [ -n "${1:-}" ]; do
+  case "$1" in
+    -s | --source)
+      src_registry="$2"; shift;;
+    -t | --target)
+      tgt_registry="$2"; shift;;
+  esac
+  shift
+done
+
+if [ -z "${tgt_registry:-}" ]; then
+  echo "tgt missing"
+  usage
+  exit 1
+fi
+
+if [ -z "${src_registry:-}" ]; then
+  uploader_kwargs="{}"
+else
+  uploader_kwargs="{remove_prefixes: [\"$src_registry\"]}"
+fi
 
 cat <<EOF
 targets:
@@ -19,8 +53,8 @@ targets:
     type: RegistriesTarget
     kwargs:
       registries:
-        - $target_registry
-      ocm_repository: $target_registry
+        - $tgt_registry
+      ocm_repository: $tgt_registry
 
 processors:
   no-op:
@@ -29,6 +63,7 @@ processors:
 uploaders:
   prepend_target:
     type: PrependTargetUploader
+    kwargs: $uploader_kwargs
 
 image_processing_cfg:
   - name: default
