patch-in effective-version (thus prevent image to lag behind)

diff --git a/.ci/build_python_packages b/.ci/build_python_packages
--- a/.ci/build_python_packages
+++ b/.ci/build_python_packages
@@ -6,6 +6,19 @@ repo_dir="$(readlink -f "$(dirname "$0")/..")"
 out_dir="$(readlink -f "${repo_dir}/../${PYPI_PATH:-}/dist")"
 mkdir "${out_dir}"
 
+if [ ! -z "${VERSION_PATH}" ]; then
+  effective_version="$(cat "${VERSION_PATH})"
+  last_release_tag_path="${repo_dir}/concourse/resources/LAST_RELEASED_TAG"
+  if [ ! -f "${last_release_tag_path}" ]; then
+    echo "ERROR: no such file ${last_release_tag_path}"
+    exit 1
+  fi
+  echo "effective-version: ${effective_version}"
+  echo "${effective_version}" > "${last_release_tag_path}"
+else
+  echo "WARNING: local build - LAST_RELEASED_TAG will not be patched"
+fi
+
 cd $repo_dir
 
 # install build-only dependencies (no need to include in image)
