re-enable tests

diff --git a/.ci/test b/.ci/test
--- a/.ci/test
+++ b/.ci/test
@@ -2,26 +2,24 @@
 
 set -e
 
-exit 0
+if ! which pytest &>/dev/null; then
+  echo "pytest is required (install with pip(3) install pytest)"
+  exit 1
+fi
 
-# if ! which pytest &>/dev/null; then
-#   echo "pytest is required (install with pip(3) install pytest)"
-#   exit 1
-# fi
+# HACK: install pytimeparse to fix unittests until next release -> remove again
+pip3 install pytimeparse
 
-# # HACK: install pytimeparse to fix unittests until next release -> remove again
-# pip3 install pytimeparse
+# usage: $1: <src-dir>
 
-# # usage: $1: <src-dir>
+src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"
 
-# src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"
+# pip3 install --upgrade -r "${src_dir}/requirements.txt"
 
-# # pip3 install --upgrade -r "${src_dir}/requirements.txt"
-
-# if PYTHONPATH="${src_dir}:${PYTHONPATH:-}" pytest "${src_dir}" "${@}"; then
-#     echo 'Unittest executions succeeded'
-#     exit 0
-# else
-#     echo 'Errors were found whilst executing unittests (see above)'
-#     exit 1
-# fi
+if PYTHONPATH="${src_dir}:${PYTHONPATH:-}" pytest "${src_dir}" "${@}"; then
+    echo 'Unittest executions succeeded'
+    exit 0
+else
+    echo 'Errors were found whilst executing unittests (see above)'
+    exit 1
+fi
