silence install-gha-libs action some more
install-gha-libs is run quite often, and typically its output is only of
interest in case of errors. Hence silence it some more.

diff --git a/.github/actions/install-gardener-gha-libs/action.yaml b/.github/actions/install-gardener-gha-libs/action.yaml
--- a/.github/actions/install-gardener-gha-libs/action.yaml
+++ b/.github/actions/install-gardener-gha-libs/action.yaml
@@ -37,7 +37,11 @@ runs:
         if not which pip &>/dev/null; then
           pip=pip3
         fi
-        $pip install setuptools >/dev/null
+        if not $pip install setuptools &>/tmp/install.log; then
+          cat /tmp/install.log
+          echo 'failed to install setuptools'
+          exit 1
+        fi
 
         version=$(.ci/read-version)
         if [[ "${version}" == *-* ]]; then
@@ -74,5 +78,3 @@ runs:
             cat /tmp/pip-install.log
             exit 1
         fi
-
-        pip show gardener-gha-libs
