factor `release(-to-pypi)` into params-step
deduplicate clunky dereferentiation of potentially undefined params.

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -17,6 +17,8 @@ jobs:
   params:
     runs-on: ubuntu-latest
     outputs:
+      release: ${{ steps.params.outputs.release }}
+      release_to_pypi: ${{ steps.params.outputs.release_to_pypi }}
       ocm_repository: ${{ steps.params.outputs.ocm_repository }}
       oci_repository: ${{ steps.params.outputs.oci_repository }}
       oci_platforms: ${{ steps.params.outputs.oci_platforms }}
@@ -36,14 +38,29 @@ jobs:
             # XXX this is a debugging / testing artefact
             ocm_repository=${releases_repo}
             oci_repository=${releases_repo}
+            release=true
+            release_to_pypi=true
           else
             ocm_repository=${snapshots_repo}
             oci_repository=${snapshots_repo}
+            release=false
+            release_to_pypi=false
           fi
+
+          if ! ${release} && ${release_to_pypi}; then
+            echo "Error: release_to_pypi must only be done in conjunction with release"
+            exit 1
+          fi
+
+          echo "release: ${release}"
+          echo "release_to_pypi: ${release_to_pypi}"
 
           echo "ocm_repository=${ocm_repository}" >> "${GITHUB_OUTPUT}"
           echo "oci_repository=${oci_repository}" >> "${GITHUB_OUTPUT}"
           echo "oci_platforms=linux/amd64,linux/arm64" >> "${GITHUB_OUTPUT}"
+
+          echo "release=${release}" >> "${GITHUB_OUTPUT}"
+          echo "release_to_pypi=${release_to_pypi}" >> "${GITHUB_OUTPUT}"
 
           echo "gcp_project=gardener-project" >> "${GITHUB_OUTPUT}"
           echo "service_account=ocm-ci-opensource@gardener-project.iam.gserviceaccount.com" \
@@ -212,7 +229,7 @@ jobs:
           workload_identity_provider: ${{ needs.params.outputs.workload_identity_provider }}
       - name: Create Release and Bump-Commits
         id: releasecommit
-        if: ${{ inputs.release }}
+        if: ${{ needs.params.outputs.release == true }}
         run: |
           echo "gha-creds*" >> .git/info/exclude
           git config --global --add safe.directory /__w/cc-utils/cc-utils
@@ -269,7 +286,7 @@ jobs:
             }' \
             > component-descriptor.yaml
 
-          if ${{ inputs.release || false }}; then
+          if ${{ needs.params.outputs.release }}; then
             commit_digest=${{ steps.releasecommit.outputs.release_commit_digest || '' }}
           else
             commit_digest=${{ github.sha }}
@@ -458,7 +475,7 @@ jobs:
         .ci/test
 
   pypi:
-    if: ${{ inputs.release-to-pypi }}
+    if: ${{ needs.params.outputs.release_to_pypi == true }}
     runs-on: ubuntu-latest
     name: Publish to PYPI
     needs:
